### ISSUE TITLE
Penetration testing review

### ISSUE THREAD

**Issue by ryankikta** [OSC-CSC480SP16/Roots-engine-R1#71]
Review tomcat server logs penetration attempt for pi.cs server.

**Comment by nedingto** [comment]
About an hour to figure out what this is and 2 hours to fix.  3 hours total.

**Comment by nedingto** [comment]
It would appear that this is an inherent issue tied to PI.  This could potentially be solved by using an alternate server but other than that, it does not seem possible to resolve.
