### ISSUE TITLE
Sql injection handling

### ISSUE THREAD

**Issue by nedingto** [OSC-CSC480SP16/Roots-engine-R1#82]
This should take about an hour to research and 2 hours to implement

**Comment by nedingto** [comment]
This explains how we will implement this https://github.com/felixge/node-mysql#escaping-query-values.

**Comment by mtrudeau314** [comment]
This might already be done for us? Don't work on this issue until we know more.

**Comment by nedingto** [comment]
Finished, took about 5 hours
